### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by aparajita** [rdlabo-team/capacitor-plugin-to-v4#1]
Thanks for this tool! Might I suggest that you not change these:

```
const changePackageVersion = {
  '"prettier"': '2.3.0',
  '"prettier-plugin-java"': '1.0.2',
  '"typescript"': '4.1.5',
```

First of all, those are old versions you have there, and AFAIK changing those has little to do with Capacitor 4 vs 3. Second, I think using a "^" version is much preferred to an absolute version, since that allows non-breaking updates.

**Comment by rdlabo** [comment]
Thanks try!!

> First of all, those are old versions you have there, and AFAIK changing those has little to do with Capacitor 4 vs 3. Second, I think using a "^" version is much preferred to an absolute version, since that allows non-breaking updates.

You have a point. However, I think I should go along with this change:
https://github.com/ionic-team/create-capacitor-plugin/commit/03027bf603626ebfdba084cb9d9a1a359d008554#diff-cc6c1148b29b0a3557c98667922f21a2394e4a8348267169c6d1243d835f7c08

**Comment by aparajita** [comment]
Yeah, well I'm not too thrilled with their dev setup in general, so I don't take anything they do as an example. Not only are they are sticking with really old versions of packages, they are using ~ ranges, which limits updates to patches. Huh? I really don't know of anyone who is still doing that. The npm default is ^ ranges.

**Comment by rdlabo** [comment]
This process does not rewrite '~' or `^`. Only the version number is rewritten using regular expressions.

But I'm just concerned that the version is older than the latest version. I feel that it should at least be rewritten in comparison.

**Comment by aparajita** [comment]
I would suggest that you should not be changing people's individual choices for their versions of those packages. It has nothing to do with the functionality of Capacitor 4.
