### ISSUE TITLE
Problem with Xcode project modification

### ISSUE THREAD

**Issue by aparajita** [rdlabo-team/capacitor-plugin-to-v4#2]
This line is missing the terminating semicolon, which completely breaks the project since Xcode can't parse it.

https://github.com/rdlabo-team/capacitor-plugin-to-v4/blob/ebfeeb73f87ac520ac9c616d23a2fe76dfe06488/src/index.ts#L161

Also, it would be nice to check if that line already exists before adding it again.

**Comment by rdlabo** [comment]
Thanks for the Issue. It seems to have broken somewhere. I fixed it!

**Comment by rdlabo** [comment]
released v1.0.3🎉

**Comment by rdlabo** [comment]
I've made the code more power efficient, so if you run the latest version again, it will fix the problem.
